[window]
opacity = 0.6

[window.dimensions]
columns = 100
lines = 25

[font]
size = 11
[font.normal]
family = "LXGW WenKai Mono"
[font.bold]
family = "LXGW Wenkai Mono"
[font.italic]
family = "LXGW WenKai Mono"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"
#dim_foreground = "#CDD6F4"
bright_foreground = "#ffffff"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]
foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]
foreground = "#282a36"
background = "#f8f8f2"

[colors.hints.start]
foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]
foreground = "#f1fa8c"
background = "#282a36"

[colors.selection]
text = "CellForeground"
background = "#44475a"

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.line_indicator]
foreground = "None"
background = "None"

#[[colors.indexed_colors]]
#index = 16
#color = "#FAB387"

#[[colors.indexed_colors]]
#index = 17
#color = "#F5E0DC"
